inherit_from: ../../.rubocop.yml

# Anonymous controllers in specs cannot access described_class
# https://github.com/rubocop/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/described_class.rb#L36-L39
RSpec/DescribedClass:
  SkipBlocks: true
